// <auto-generated />
using MVC_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231118023900_Create_table_orderDetail")]
    partial class Create_table_orderDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("MVC_Project.Models.Person", b =>
                {
                    b.Property<int>("Personid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Personid");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("MVC_Project.Models.orderDetail", b =>
                {
                    b.Property<int>("order_detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("num")
                        .HasColumnType("INTEGER");

                    b.Property<int>("order_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("room_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("order_detail_id");

                    b.ToTable("orderDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
